name: Missing Service in Region
description: Report a service that is missing from an existing region on the map
title: "[Missing Service]: "
labels: ["data-correction", "missing-service"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping keep the Veeam Data Cloud Services Map accurate! 
        Please provide as much detail as possible about the missing service.

  - type: dropdown
    id: provider
    attributes:
      label: Cloud Provider
      description: Which cloud provider is this region in?
      options:
        - AWS
        - Azure
    validations:
      required: true

  - type: input
    id: region-name
    attributes:
      label: Region Name
      description: The name of the region (e.g., "US East 1 (N. Virginia)" or "West Europe")
      placeholder: "US East 1 (N. Virginia)"
    validations:
      required: true

  - type: input
    id: region-code
    attributes:
      label: Region Code (if known)
      description: The provider's region code (e.g., "us-east-1" or "westeurope")
      placeholder: "us-east-1"
    validations:
      required: false

  - type: dropdown
    id: service
    attributes:
      label: Missing Service
      description: Which service is missing from this region?
      options:
        - VDC Vault (vdc_vault)
        - VDC for Microsoft 365 (vdc_m365)
        - VDC for Entra ID (vdc_entra_id)
        - VDC for Salesforce (vdc_salesforce)
        - VDC for Azure (vdc_azure_backup)
    validations:
      required: true

  - type: dropdown
    id: vault-edition
    attributes:
      label: VDC Vault Edition (if applicable)
      description: If the missing service is VDC Vault, which edition is missing?
      options:
        - N/A - Not VDC Vault
        - Foundation
        - Advanced
    validations:
      required: false

  - type: dropdown
    id: vault-tier
    attributes:
      label: VDC Vault Tier (if applicable)
      description: If the missing service is VDC Vault, is this a Core or Non-Core region?
      options:
        - N/A - Not VDC Vault
        - Core
        - Non-Core
    validations:
      required: false

  - type: textarea
    id: source
    attributes:
      label: Source / Evidence
      description: |
        Please provide a link or reference to where you found this information.
        This helps us verify the data before updating the map.
      placeholder: |
        - Link to Veeam documentation
        - Screenshot from Veeam console
        - Other source
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
    validations:
      required: false
